// Code generated by hertz generator.

package main

import (
	"douyinV/cmd/publish/rpc"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

func main() {
	h := server.Default()
	err := rpc.Init()
	if err != nil {
		hlog.Fatal("rpc初始化失败")
		panic("rpc初始化失败")
		return
	}

	register(h)
	h.Spin()
}
