// Code generated by hertz generator.

package message

import (
	"context"
	"strconv"
	"tiktok/biz/rpc"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	message "tiktok/biz/model/message"
)

// Action .
// @router douyin/message/action [POST]
func Action(ctx context.Context, c *app.RequestContext) {
	var err error
	var req message.ActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	fromUID, _ := strconv.Atoi(req.Token)
	resp := rpc.Action(fromUID, int(req.ToUserID), int(req.ActionType), req.Content)

	c.JSON(consts.StatusOK, resp)
}
