// Code generated by hertz generator.

package message

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	message "tiktok/biz/model/message"
)

// Action .
// @router douyin/message/action [POST]
func Action(ctx context.Context, c *app.RequestContext) {
	var err error
	var req message.ActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(message.ActionResp)

	c.JSON(consts.StatusOK, resp)
}
