// Code generated by hertz generator.

package message

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	message "tiktok/biz/model/message"
)

// Chat .
// @router douyin/message/chat [GET]
func Chat(ctx context.Context, c *app.RequestContext) {
	var err error
	var req message.ChatReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(message.ChatResp)

	c.JSON(consts.StatusOK, resp)
}
