// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"tiktok/config"
)

func main() {
	config.Init()

	h := server.Default(server.WithHostPorts(config.ClientUrlHostNamePORT))

	register(h)
	h.Spin()
}
