// Code generated by hertz generator.

package feed

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	feed "tiktok/biz/model/feed"
	"tiktok/mock"
)

// Feed .
// @router douyin/feed [GET]
func Feed(ctx context.Context, c *app.RequestContext) {
	var err error
	var req feed.FeedReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := feed.FeedResp{
		StatusCode: 0,
		VideoList:  mock.GetVideos(),
	}

	c.JSON(consts.StatusOK, resp)
}
